spring.application.name=project-hub
spring.main.lazy-initialization=true
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/project_hub
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always

