CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255),
    started_at  DATE,
    finished_at DATE,
    status VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS
    project_tech_stack (
        project_id BIGINT NOT NULL REFERENCES project(id),
    tech_stack  VARCHAR(255)
    );